### ISSUE TITLE
Feature Request: Pressure Sensor & Pump Control

### ISSUE THREAD

**Issue by CaptInsano** [shmick/PID-Controller#11]
Really interested in this project, I am looking to add a PID to my Gaggia Classic but really wanted it to be smart (added to my homeassistant setup) just like your system. I also love the fact that the  external of the machine is untouched.

Would it be possible to add a water pressure sensor to this setup?

Something like this:  https://www.amazon.co.uk/Qiman-Pressure-Converter-Sensor-Transmitter/dp/B07MW4MJFG

discussion about adding it to tasmota here:  https://github.com/arendst/Tasmota/issues/6000

It would cool to see the pressure profile over time and possibly add pressure control by pulsing the pump via SSR.
topic regarding same here: http://www.gaggiausersgroup.com/index.php?topic=990.0 

The addition of a pump control SSR would also allow running perfectly timed shots.

Great work!

**Comment by rvt** [comment]
Loos interesting for my little project aswell...
How is the ressure sensor attached to the Gaggia? I could not find that in the link yet...

I am working for something similar here (writing the code myself to keep me buzy) https://github.com/rvt/espgaggia

**Comment by CaptInsano** [comment]
I was thinking of attaching it via a T-junction between the pump and the group head like the tradition pressure sensors.

![image](https://user-images.githubusercontent.com/332478/111219638-2e374d00-85d0-11eb-9dc0-462fbfb8c808.png)

**Comment by shmick** [comment]
@CaptInsano,

I don't have plans to add any additional functionality to the project at the moment. I'm only using 1 of the 4 ADS1115 inputs, so adding an analog pressure transducer to one of the free inputs should work fine. Keep in mind that you'll want to put the output through a voltage divider as the ADS1115 is running off 3.3v and the transducer is 0-5v.

Even 1 SSR + the PCB inside the case is a tight fit, so I'd be wary of adding a 2nd SSR to control the pump.

I originally had an OLED display to watch the temperature and ended up not using it because I know after 8 minutes or so that the machine is at temp and now I can use Home Assistant to verify that as well.

The HA integration was more so that I could remotely fire up the boiler any time so that the machine was ready to go without me having to wait for it to warm up.

I'm also not concerned about the pressure readout, but if I did want to know, I'd probably go with the analog kit, otherwise I'd need to re-add the OLED display or keep an eye on HA as the shot is being pulled, which isn't something I'm too interested in doing.

If you'd like to add the functionality, feel free to do so and send me a pull request!

Cheers.
