### ISSUE TITLE
K Type Thermocouple

### ISSUE THREAD

**Issue by tkaldridge88** [shmick/PID-Controller#2]
Have you had any issues with the accuracy of the thermocouple? Have you considered NTCs or RTDs? Thanks for all the information and hard work. I am planning to collect all the hardware this week to replicate your project.

Thanks, Kyle

**Comment by shmick** [comment]
Hi Kyle,

The accuracy of the thermocouple is fine. The 10 bit ADC on the MCU was lacking in resolution, which is why I added the ADS1115 15 bit ADC into the mix.

I've been using a DS18B20 1-Wire thermometer in another project and it's working well.

**Comment by tkaldridge88** [comment]
Thanks for the quick reply!

Are you still using the QIDI K thermocouple with this setup? Or different brand?

Do you happen to have a wiring sketch utilizing the ADS1115 with the AD8495? I'm far from an expert but could probably fumble my way through the design if not. Thanks for sharing your code!

**Comment by shmick** [comment]
Still using the QIDI K, mostly because it has a 4mm end that threads into the 4mm hole on the boiler on the Gaggia.

Here's a schematic I started on, but haven't touched in a while:

https://imgur.com/nLn90YN

Here's the PCB layout I've got designed but haven't had made yet. I'm still running a crude protoboard setup.

https://imgur.com/OjCZa3f

**Comment by shmick** [comment]
Closed
