### ISSUE TITLE
wiring + photo of build

### ISSUE THREAD

**Issue by xpokor02** [shmick/PID-Controller#3]
Hi,
Do you have wiring diagram or text description of wiring? Plus I would love to see photo of your build how it look together. 
Thanks

**Comment by shmick** [comment]
The wiring diagram is shown at https://github.com/shmick/Espresso-PID-Controller/blob/master/single_ssr_120v.png

I've removed the the coffee thermostat and replaced it with a thermocouple. The relay now controls the power to the boiler rather than the bimetal thermostat. The steam thermostat is also not required as you can set the temperature to whatever you want.

**Comment by xpokor02** [comment]
Hi shmick,
thanks for that, but I was also interested in seeing built and wiring of PID itself and how you integrated it into machine.
Thanks

**Comment by shmick** [comment]
FYI I've added a some PCB files to the repo and you can see how I've got things integrated in a thread [here](https://coffeeforums.co.uk/topic/56699-my-espresso-pid-controller/).
